server:
  port: 8081

# 生产环境配置（使用 Nacos 配置中心）
spring:
  config:
    import:
      - optional:nacos:valhalla-user.yaml?refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: nacos-standalone-derby:8848
        namespace: prod
        group: DEFAULT_GROUP

logging:
  level:
    root: WARN
    com.yggdrasil.labs.*: WARN
