server:
  port: 8081

# 测试环境配置（使用 Nacos 配置中心）
spring:
  config:
    import:
      - optional:nacos:valhalla-user.yaml?refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: nacos-standalone-derby:8848
        namespace: test
        group: DEFAULT_GROUP

logging:
  level:
    root: INFO
    com.yggdrasil.labs.**.mapper: DEBUG
