server:
  port: 8081

# 开发环境配置（使用 Nacos 配置中心）
spring:
  config:
    import:
      - optional:nacos:valhalla-user.yaml?refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: nacos-standalone-derby:8848
        namespace: dev
        group: DEFAULT_GROUP
        # 启用配置刷新
        refresh-enabled: true

logging:
  level:
    root: INFO
    # 保留 SQL 日志（DEBUG 级别）
    com.yggdrasil.labs.**.mapper: DEBUG
